Repository SOPT-all/36-COLLABORATION-WEB-HANATOUR, pull requests merged in 2025-05, with the labels that each got.

#7 [Setting] Auto reviewer setting
  .github/CODEOWNERS
Labels: ⚙️ Setting

#8 [Setting] Storybook 초기 세팅
  .gitignore
  .storybook/main.ts
  .storybook/preview.ts
  .storybook/vitest.setup.ts
  package.json
  src/stories/README.md
  vitest.workspace.ts
  yarn.lock
Labels: ⚙️ Setting

#10 [Setting] eslint prettier 설정
  .eslintignore
  .gitignore
  .prettierignore
  .prettierrc
  .vscode/settings.json
  eslint.config.js
  package.json
  yarn.lock
Labels: ⚙️ Setting

#11 [Setting] 절대경로 설정
  package.json
  tsconfig.json
  vite.config.ts
  yarn.lock
Labels: ⚙️ Setting

#12 [Setting] react router 설치
  package.json
  yarn.lock
Labels: ⚙️ Setting

#15 [Setting] design system 설정
  package.json
  src/App.css
  src/index.css
  src/shared/styles/.gitkeep
  src/shared/styles/global.css
  src/shared/styles/theme.css
  vite.config.ts
  yarn.lock
Labels: ⚙️ Setting

#17 [Setting] Tanstack Query 설정
  package.json
  src/App.tsx
  src/queryClient.ts
  src/shared/apis/http.ts
  tsconfig.json
Labels: 🔧 Fix, ⚙️ Setting

#13 [Setting] Axios instance 설정
  package.json
  src/shared/apis/http.ts
  yarn.lock
Labels: ⚙️ Setting

#18 [Setting] 초기 세팅 점검
  .gitignore
  .prettierrc
  .vscode/settings.json
  eslint.config.js
  package.json
  src/App.tsx
  src/index.css
  src/layout/.gitkeep
  src/layout/Layout.tsx
  src/main.tsx
  src/pages/home/Home.tsx
  src/pages/search/Search.tsx
  src/queryClient.ts
  src/routes/.gitkeep
  src/routes/router.tsx
  src/routes/routesConfig.ts
  src/shared/apis/http.ts
  src/shared/components/.gitkeep
  src/shared/components/Header/Header.tsx
  tsconfig.app.json
  tsconfig.json
  vite.config.ts
  yarn.lock
Labels: ⚙️ Setting

#25 [Feat] Home 검색 바 컴포넌트 구현
  src/pages/home/components/SearchBar.tsx
  src/pages/home/types/index.ts
  src/shared/assets/icons/calendar.svg
  src/shared/assets/icons/checkedCircle.svg
  src/shared/assets/icons/dropDown.svg
  src/shared/assets/icons/dropUp.svg
  src/shared/assets/icons/location.svg
  src/shared/assets/icons/uncheckedCircle.svg
Labels: 🎨 Design, 🛠️ Feature

#26 [Feat] Search Header 구현
  src/pages/search/Search.tsx
  src/pages/search/components/SearchHeader.tsx
  src/shared/assets/calender.svg
  src/shared/assets/downErrow.svg
  src/shared/assets/location.svg
  yarn.lock
Labels: 🎨 Design, 🛠️ Feature

#35 [Feat] Search detail component
  src/pages/search/Search.tsx
  src/pages/search/components/SearchDetail.tsx
  src/pages/search/components/SearchDetailWrapper.tsx
  src/pages/search/components/SearchHeader.tsx
  src/pages/search/components/SearchTopFilter.tsx
  src/shared/assets/icons/calender.svg
  src/shared/assets/icons/down.svg
  src/shared/assets/icons/downErrow.svg
  src/shared/assets/icons/filter.svg
  src/shared/assets/icons/likesmall.svg
  src/shared/assets/icons/location.svg
  src/shared/assets/icons/reset.svg
  src/shared/assets/icons/searchdetailimage.png
  src/shared/assets/icons/star.svg
  src/shared/assets/icons/upErrow_purple.svg
  src/shared/assets/location.svg
  src/shared/styles/theme.css
Labels: 🎨 Design, 🛠️ Feature

#40 [Feat] search view more product 구현
  public/searchdetailimage.png
  src/pages/home/components/.gitkeep
  src/pages/home/components/SearchBar.tsx
  src/pages/search/components/.gitkeep
  src/pages/search/components/SearchDetail.tsx
  src/pages/search/components/SearchDetailCalendar.tsx
  src/pages/search/components/SearchDetailViewMore.tsx
  src/pages/search/components/SearchDetailViewMoreInfo.tsx
  src/pages/search/components/SearchDetailWrapper.tsx
  src/pages/search/components/SearchHeader.tsx
  src/pages/search/components/SearchTopFilter.tsx
  src/pages/search/datas/CalendarData.json
  src/pages/search/datas/SearchDetailMock.json
  src/shared/assets/icons/arrowLeft.svg
  src/shared/assets/icons/arrowLeft_small.svg
  src/shared/assets/icons/arrowRight.svg
  src/shared/assets/icons/arrowRight_small.svg
  src/shared/assets/icons/arrowUp_black.svg
  src/shared/assets/icons/dropUp.svg
  src/shared/assets/icons/dropUp_purple.svg
  src/shared/assets/icons/memoIcon.svg
  src/shared/styles/theme.css
Labels: 🎨 Design, 🛠️ Feature

#43 [Feat] Home 출발지 선택 모달
  src/pages/home/components/DepartureModal.tsx
Labels: 🎨 Design, 🛠️ Feature

#29 [Feat] Headless Accordion 컴포넌트 구현
  src/shared/assets/icons/downIcon_gray.svg
  src/shared/assets/icons/upIcon_black.svg
  src/shared/components/Accordion/Accordion.tsx
  src/shared/components/Accordion/Content.tsx
  src/shared/components/Accordion/Header.tsx
Labels: 🎨 Design, 🛠️ Feature

#44 [Feat] Home 여행일자 선택 - 캘린더 모달 커스텀
  package.json
  src/pages/home/components/CalendarModal.tsx
  src/shared/assets/icons/chevronLeftIcon.svg
  src/shared/assets/icons/chevronRightIcon.svg
  src/shared/assets/icons/disabledChevIcon.svg
  src/shared/styles/react-calendar.css
  src/shared/styles/theme.css
  yarn.lock
Labels: 🎨 Design, 🛠️ Feature

#49 [Feat] Announcement 컴포넌트 구현
  src/shared/assets/icons/facebook.svg
  src/shared/assets/icons/instagram.svg
  src/shared/assets/icons/kakaoChannel.svg
  src/shared/assets/icons/kakaostory.svg
  src/shared/assets/icons/naverblog.svg
  src/shared/assets/icons/youtube.svg
  src/shared/components/Announcement/Announcement.tsx
Labels: 🎨 Design, 🛠️ Feature

#47 [Feat] Search page filter list 구현
  src/pages/search/components/SearchFilterList/SearchFilterList.tsx
  src/pages/search/constants/filter.ts
  src/pages/search/hooks/useSearchFilters.ts
  src/shared/assets/icons/checkbox.svg
  src/shared/assets/icons/flightFilterIcon.svg
  src/shared/assets/icons/groupTourFilterIcon.svg
  src/shared/assets/icons/noFlightFilterIcon.svg
  src/shared/assets/icons/non_checkbox.svg
  src/shared/assets/icons/ourTourFilterIcon.svg
  src/shared/assets/images/slider.svg
  src/shared/components/Accordion/Accordion.tsx
Labels: 🎨 Design, 🛠️ Feature

#48 [Feat] Home SearchBar - Modal 연동
  package.json
  src/pages/home/components/CalendarModal.tsx
  src/pages/home/components/DepartureModal.tsx
  src/pages/home/components/DestinationModal.tsx
  src/pages/home/components/ModalBase.tsx
  src/pages/home/components/SearchBar.tsx
  yarn.lock
Labels: 🎨 Design, 🛠️ Feature

#56 [Setting] 배포 unused 옵션 변경
  tsconfig.app.json
Labels: ⚙️ Setting, 🌈 Deploy

#54 [API] Home 메인 검색 API 연동 (Tanstack-Query & Axios)
  package.json
  src/pages/home/apis/postMainSearch.ts
  src/pages/home/apis/postMainSearchQuery.ts
  src/pages/home/components/CalendarModal.tsx
  src/pages/home/components/SearchBar.tsx
  src/shared/apis/http.ts
  yarn.lock
Labels: 🧲 API

#60 [Feat] Promotion 쿼카 배너 & 광고 배너 구현
  src/pages/home/Home.tsx
  src/pages/home/components/AdvertisementBanner.tsx
  src/pages/home/components/PromotionBanner.tsx
  src/shared/assets/images/advertisement_banner.svg
  src/shared/assets/images/promotion_banner_image.svg
  src/shared/assets/images/promotion_banner_middle_image.svg
  src/shared/assets/images/promotion_banner_right_image.svg
Labels: 🎨 Design, 🛠️ Feature

#64 [Feat] Home 상단 배너 구현
  src/pages/home/Home.tsx
  src/pages/home/components/ModalBase.tsx
  src/pages/home/components/SearchBar.tsx
  src/pages/home/components/TopBanner.tsx
  src/shared/assets/icons/leftArrowIcon.svg
  src/shared/assets/icons/pauseIcon.svg
  src/shared/assets/icons/rightArrowIcon.svg
  src/shared/assets/images/top_banner_bg.svg
Labels: 🎨 Design, 🛠️ Feature

#65 [Feat] Footer 구현하기
  src/shared/assets/icons/footerEllipse.svg
  src/shared/assets/icons/footerHeadset.svg
  src/shared/assets/icons/footerLeftArrow.svg
  src/shared/assets/icons/footerLine.svg
  src/shared/assets/icons/footerRightArrow.svg
  src/shared/assets/icons/footerUnderline1.svg
  src/shared/assets/icons/footerUnderline2.svg
  src/shared/assets/icons/footerUnderline3.svg
  src/shared/assets/images/footerBrandImage01.png
  src/shared/assets/images/footerBrandImage02.png
  src/shared/assets/images/footerBrandImage03.png
  src/shared/assets/images/footerBrandImage04.png
  src/shared/assets/images/footerBrandImage05.png
  src/shared/assets/images/footerBrandImage06.png
  src/shared/assets/images/footerBrandImage07.png
  src/shared/assets/images/footerBrandImage08.png
  src/shared/assets/images/footerBrandImage09.png
  src/shared/components/Footer/Footer.tsx
Labels: 🎨 Design, 🛠️ Feature

#61 [Feat] search page api 연동
  src/pages/search/Search.tsx
  src/pages/search/components/FloatingButton.tsx
  src/pages/search/components/SearchDetail.tsx
  src/pages/search/components/SearchDetailViewMoreInfo.tsx
  src/pages/search/components/SearchDetailWrapper.tsx
  src/pages/search/components/SearchFilterList/SearchFilterList.tsx
  src/pages/search/components/SearchTopFilter.tsx
  src/pages/search/hooks/useSearchFilters.ts
  src/shared/apis/getSearchFilterHttp.ts
  src/shared/apis/getSearchFilterQuery.ts
  src/shared/apis/http.ts
  src/shared/assets/icons/arrowDown_lightgray.svg
  src/shared/styles/theme.css
Labels: 🧲 API

#66 [Feat] Home 페이지 컴포넌트 연결 및 퍼블리싱
  src/pages/home/Home.tsx
  src/pages/home/components/AdvertisementBanner.tsx
  src/pages/home/components/PromotionBanner.tsx
  src/pages/home/components/SearchBar.tsx
  src/pages/home/components/SingaporeBanner.tsx
  src/pages/search/components/SearchFilterList/SearchFilterList.tsx
  src/shared/assets/images/food_banner_image.svg
  src/shared/components/Announcement/Announcement.tsx
  src/shared/components/Card/CardContainer.tsx
  src/shared/components/Card/CircleCardL.tsx
  src/shared/components/Card/CircleCardS.tsx
  src/shared/components/Card/RectCardBottom.tsx
  src/shared/components/Card/RectCardFood.tsx
  src/shared/components/Card/RectCardMini.tsx
  src/shared/components/Card/RectCardTop.tsx
  src/shared/components/Filter/Filter.tsx
  src/shared/components/Title/Title.tsx
Labels: 🎨 Design, 🛠️ Feature

#72 [Chore] Meta tag 추가 및 파비콘/타이틀 업데이트
  index.html
  public/favicon.svg
  public/og-image.png
Labels: 🎸 Chore
